dist: bionic
language: node_js
node_js:
- 10
- 12
- 14
deploy:
  provider: npm
  email: jan@janraasch.com
  api_key:
    secure: Afxp+TCrRVq74KctrVDe/pq7kEE7HIMJtBbl+fFkaWgTs1lh/rWSNiru5/IR5kPEzwGL+SiswBpUYCjp6SZAM99hrPoQiLrdHaNfm30bhURiEeuVZuDB+yl1ImcmhGhYg4uPycQkGG2dTC2/j1A/gt0DCTM9EjQ1CzRlbSmhBds=
  on:
    tags: true
    repo: janraasch/javascript-commitment
    node: 12
    branch: master
