sudo: false
language: node_js
node_js:
- '0.10'
- '0.12'
- iojs
deploy:
  provider: npm
  email: jan@janraasch.com
  api_key:
    secure: KUvxS3p24a0cYTfGsIBlnf/I7XiCG2P5Zp9MjR87vivOwfMf3Su6mwHhOqyodpoGT+ZoEm9atgwHhLSfxfhyI9US6PTeRB1L7Bl1qEgodkC1zYwbfCkMp1+bkpJAiguazd2Iz/Cy7VtRESdIEdUpaBo/vY6HpU6DyLovplEjoUM=
  on:
    tags: true
    repo: janraasch/javascript-commitment
    node: '0.12'
    branch: master
